---
- delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: create the data-usage-api-configs secret
      run_once: true
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: data-usage-api-configs
            namespace: "{{ ns }}"
          data:
            data-usage-api.yml: "{{ lookup('template', 'data-usage-api.yml.j2') | b64encode }}"
      when: load_configs is undefined or (load_configs | bool)

    - ansible.builtin.include_role:
        name: deploy-service
        tasks_from: main
      vars:
        project_name: data-usage-api
