---
- name: Configure argo Kubernetes resources
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Create the argo namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ argo_ns }}"

    - name: Create the argo events namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ argo_events_ns }}"

    - name: Install argo
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'install.yaml') | from_yaml_all }}"

    - name: Create argo-executor role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"
          rules:
            - apiGroups:
                - argoproj.io
              resources:
                - workflowtaskresults
              verbs:
                - create
                - delete
                - apply
                - patch

    - name: Create the argo-executor service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"

    - name: Create the argo-executor role-binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ClusterRoleBinding
          metadata:
            name: argo-executor-binding
            namespace: "{{ argo_ns }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: argo-executor
            namespace: "{{ argo_ns }}"
          subjects:
            - kind: ServiceAccount
              name: argo-executor
              namespace: "{{ argo_ns }}"

    - name: Install argo-events
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_install.yaml') | from_yaml_all }}"

    - name: Install argo-events eventbus
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_eventbus_install.yaml') | from_yaml_all }}"

    - name: Install argo-events sensor rbac
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_sensor_rbac.yaml') | from_yaml_all }}"
