---
- name: Configure argo Kubernetes resources
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Create the argo namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ argo_ns }}"

    - name: Create the argo events namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ argo_events_ns }}"

    - name: Install argo
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'install.yaml') | from_yaml_all }}"

    - name: Create argo-executor role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"
          rules:
            - apiGroups:
                - argoproj.io
              resources:
                - workflowtaskresults
              verbs:
                - create
                - delete
                - apply
                - patch

    - name: Create the argo-executor service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: argo-executor
            namespace: "{{ argo_ns }}"

    - name: Create the argo-executor role-binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ClusterRoleBinding
          metadata:
            name: argo-executor-binding
            namespace: "{{ argo_ns }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: argo-executor
          subjects:
            - kind: ServiceAccount
              name: argo-executor
              namespace: "{{ argo_ns }}"

    - name: Install argo-events
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_install.yaml') | from_yaml_all }}"

    - name: Install argo-events eventbus
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_eventbus_install.yaml') | from_yaml_all }}"

    - name: Install argo-events sensor rbac
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'argo_events_sensor_rbac.yaml') | from_yaml_all }}"

    - name: Add the irods-config configmap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: irods-config
            namespace: "{{ argo_ns }}"
          data:
            IRODS_HOST: "{{ irods_host }}"
            IRODS_PORT: "{{ irods_port | string }}"
            IRODS_USER_NAME: "{{ irods_user }}"
            IRODS_USER_PASSWORD: "{{ irods_password }}"
            IRODS_ZONE_NAME: "{{ irods_zone }}"

    - name: Set up webhook event source
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: EventSource
          metadata:
            name: webhook
            namespace: "{{ argo_events_ns }}"
          spec:
            service:
              ports:
                - port: 80
                  targetPort: 80
            webhook:
              # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
              batch-status:
                # port to run HTTP server on
                port: "80"
                # endpoint to listen to
                endpoint: /batch
                # HTTP request method to allow. In this case, only POST requests are accepted
                method: POST

              batch-cleanup:
                port: "80"
                endpoint: /batch/cleanup
                method: POST

              vice-status:
                port: "80"
                endpoint: /vice
                method: POST

    - name: Set up a logging sensor for the webhook event
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Sensor
          metadata:
            name: webhook-logging
            namespace: "{{ argo_events_ns }}"
          spec:
            dependencies:
              - name: batch-status-dep
                eventSourceName: webhook
                eventName: batch-status
            triggers:
              - template:
                  name: log-batch-status
                  log:
                    intervalSeconds: 1

    - name: Set up a cleanup sensor for the webhook event
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Sensor
          metadata:
            name: cleanup-batch-workflow
            namespace: "{{ argo_events_ns }}"
          spec:
            dependencies:
              - name: cleanup-batch-dep
                eventSourceName: webhook
                eventName: batch-cleanup
            triggers:
              - template:
                  name: cleanup-batch-trigger
                  http:
                    url: "http://app-exposer.{{ ns }}/batch/cleanup"
                    headers:
                      Content-Type: application/json
                    payload:
                      - src:
                          dependencyName: cleanup-batch-dep
                          dataKey: body.uuid
                        dest: uuid
                    method: POST
                retryStrategy:
                  steps: 3
                  duration: 3s

    - name: Set up a job-status-listener sensor for the webhook event
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Sensor
          metadata:
            name: webhook-jsl
            namespace: "{{ argo_events_ns }}"
          spec:
            dependencies:
              - name: batch-status-dep
                eventSourceName: webhook
                eventName: batch-status
            triggers:
              - template:
                  name: send-to-job-status-listener
                  http:
                    url: "http://job-status-listener.{{ ns }}/status/batch"
                    headers:
                      Content-Type: application/json
                    payload:
                      - src:
                          dependencyName: batch-status-dep
                          dataKey: body.job_uuid
                        dest: job_uuid
                      - src:
                          dependencyName: batch-status-dep
                          dataKey: body.hostname
                        dest: hostname
                      - src:
                          dependencyName: batch-status-dep
                          dataKey: body.message
                        dest: message
                      - src:
                          dependencyName: batch-status-dep
                          dataKey: body.state
                        dest: state
                    method: POST
                retryStrategy:
                  steps: 3
                  duration: 3s
