---
- name: Install and configure Keycloak
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Create the keycloak namespace
      kubernetes.core.k8s:
        name: "{{ keycloak_namespace }}"
        state: present
        kind: namespace
        api_version: v1

    - name: Create the keycloak secrets
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: dbuser
            namespace: "{{ keycloak_namespace }}"
            labels:
              app: keycloak
          type: Opaque
          data:
            username: "{{ keycloak_db_username | b64encode }}"
            password: "{{ keycloak_db_password | b64encode }}"

    - name: Create the kc-selfsigned-ca secret
      when: cert_manager_provider == 'selfsigned'
      kubernetes.core.k8s:
        name: kc-selfsigned-ca
        namespace: "{{ keycloak_namespace }}"
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: kc-selfsigned-ca
          spec:
            isCA: true
            commonName: kc-selfsigned-ca
            secretName: kc-selfsigned-ca
            duration: "{{ keycloak_cert_duration }}"
            renewBefore: "{{ keycloak_cert_renew_before }}"
            privateKey:
              algorithm: ECDSA
              size: 256
            issuerRef:
              name: default-cluster-issuer
              kind: ClusterIssuer
              group: cert-manager.io

    - name: Create the kc-ca-issuer issuer
      when: cert_manager_provider == 'selfsigned'
      kubernetes.core.k8s:
        name: kc-ca-issuer
        namespace: "{{ keycloak_namespace }}"
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: kc-ca-issuer
          spec:
            ca:
              secretName: kc-selfsigned-ca

    - name: Create the locally signed kc-tls certificate
      when: cert_manager_provider == 'selfsigned'
      kubernetes.core.k8s:
        name: kc-tls
        namespace: "{{ keycloak_namespace }}"
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: kc-tls
          spec:
            secretName: kc-tls
            duration: "{{ keycloak_cert_duration }}"
            renewBefore: "{{ keycloak_cert_renew_before }}"
            issuerRef:
              name: kc-ca-issuer
              kind: Issuer
            commonName: keycloak.{{ keycloak_namespace }}.svc.cluster.local
            dnsNames:
              - localhost
              - "{{ keycloak_hostname }}"
              - "*.keycloak.{{ keycloak_namespace }}.svc.cluster.local"
              - "*.keycloak.{{ keycloak_namespace }}.svc"
              - "*.keycloak.{{ keycloak_namespace }}"
              - "*.keycloak"
              - keycloak.{{ keycloak_namespace }}.svc.cluster.local
              - keycloak.{{ keycloak_namespace }}.svc
              - keycloak.{{ keycloak_namespace }}
              - keycloak

    - name: Create the kc-tls certificate signed by Let's Encrypt
      when: cert_manager_provider == 'letsencrypt'
      kubernetes.core.k8s:
        name: kc-tls
        namespace: "{{ keycloak_namespace }}"
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: kc-tls
          spec:
            secretName: kc-tls
            duration: "{{ keycloak_cert_duration }}"
            renewBefore: "{{ keycloak_cert_renew_before }}"
            issuerRef:
              name: "{{ cert_manager_le_issuer_name }}"
              kind: ClusterIssuer
            commonName: "{{ keycloak_hostname }}"
            dnsNames:
              - "{{ keycloak_hostname }}"

    - name: Install the keycloak deployment
      kubernetes.core.k8s:
        state: present
        wait: true
        wait_timeout: 1800
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: keycloak
            namespace: "{{ keycloak_namespace }}"
            labels:
              app: keycloak
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: keycloak
            template:
              metadata:
                labels:
                  app: keycloak
              spec:
                containers:
                  - name: keycloak
                    image: "harbor.cyverse.org/de/keycloak:{{ keycloak_version }}"
                    args:
                      - "start"
                      - "--optimized"
                    env:
                      - name: KC_BOOTSTRAP_ADMIN_USERNAME
                        value: "{{ keycloak_temp_admin_username }}"
                      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                        value: "{{ keycloak_temp_admin_password }}"
                      - name: KC_PROXY_HEADERS
                        value: "{{ keycloak_proxy_headers }}"
                      - name: KC_HTTP_ENABLED
                        value: "{{ keycloak_http_enabled }}"
                      - name: KC_HOSTNAME_STRICT
                        value: "{{ keycloak_hostname_strict }}"
                      - name: KC_HEALTH_ENABLED
                        value: "true"
                      - name: KC_METRICS_ENABLED
                        value: "true"
                      - name: KC_LOG_LEVEL
                        value: "{{ keycloak_log_level }}"
                      - name: KC_DB
                        value: "{{ keycloak_db_vendor }}"
                      - name: KC_DB_URL_DATABASE
                        value: "{{ keycloak_db_name }}"
                      - name: KC_DB_URL_HOST
                        value: "{{ groups['dbms'][0] }}"
                      - name: KC_DB_URL_PORT
                        value: "{{ keycloak_db_port }}"
                      - name: KC_DB_USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: dbuser
                            key: username
                      - name: KC_DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: dbuser
                            key: password
                      - name: JAVA_OPTS
                        value: "{{ keycloak_java_opts }}"
                    resources:
                      requests:
                        cpu: "{{ keycloak_cpu_request }}"
                        memory: "{{ keycloak_memory_request }}"
                        ephemeral-storage: "{{ keycloak_ephemeral_storage_request }}"
                      limits:
                        cpu: "{{ keycloak_cpu_limit }}"
                        memory: "{{ keycloak_memory_limit }}"
                        ephemeral-storage: "{{ keycloak_ephemeral_storage_limit }}"
                    ports:
                      - name: http
                        containerPort: 8080
                    startupProbe:
                      httpGet:
                        path: /auth/health/live
                        port: 9000
                      periodSeconds: 30
                      failureThreshold: 100
                    livenessProbe:
                      httpGet:
                        path: /auth/health/live
                        port: 9000
                      periodSeconds: 30
                      failureThreshold: 10
                    readinessProbe:
                      httpGet:
                        path: /auth/health/ready
                        port: 9000
                      periodSeconds: 30
                      failureThreshold: 10

    - name: Install the keycloak service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: keycloak
            namespace: "{{ keycloak_namespace }}"
            labels:
              app: keycloak
          spec:
            ports:
              - protocol: TCP
                name: http
                port: 80
                targetPort: http
            selector:
              app: keycloak
            type: ClusterIP

    - name: Create the gateway for Keycloak
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: Gateway
          metadata:
            name: keycloak
            namespace: "{{ keycloak_namespace }}"
          spec:
            gatewayClassName: "{{ gateway_class_name }}"
            listeners:
              - hostname: "{{ keycloak_hostname }}"
                name: keycloak-https
                port: 8443
                protocol: HTTPS
                tls:
                  certificateRefs:
                    - kind: Secret
                      group: ""
                      name: kc-tls

    - name: Define the routes for Keycloak
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: keycloak-routes
            namespace: "{{ keycloak_namespace }}"
          spec:
            hostnames:
              - "{{ keycloak_hostname }}"
            parentRefs:
              - name: keycloak
            rules:
              - backendRefs:
                  - name: keycloak
                    port: 80

    - name: Create the kcadmin secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: kcadmin
            namespace: "{{ keycloak_namespace }}"
            labels:
              app: keycloak
          type: Opaque
          data:
            username: "{{ keycloak_admin_username | b64encode }}"
            password: "{{ keycloak_admin_password | b64encode }}"
            email: "{{ keycloak_admin_email | b64encode }}"

    - name: Create the permanent admin user
      kubernetes.core.k8s:
        state: present
        wait: true
        wait_condition:
          type: Complete
          status: "True"
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: kc-create-admin-user
            namespace: "{{ keycloak_namespace }}"
          spec:
            ttlSecondsAfterFinished: 3600
            template:
              spec:
                containers:
                  - name: kc
                    image: "harbor.cyverse.org/de/keycloak:{{ keycloak_version }}"
                    imagePullPolicy: Always
                    command:
                      - create-kc-admin.sh
                    env:
                      - name: KC_ADMIN_URL
                        value: "http://keycloak/auth"
                      - name: KC_ADMIN_USER
                        valueFrom:
                          secretKeyRef:
                            name: kcadmin
                            key: username
                      - name: KC_ADMIN_PASS
                        valueFrom:
                          secretKeyRef:
                            name: kcadmin
                            key: password
                      - name: KC_ADMIN_EMAIL
                        valueFrom:
                          secretKeyRef:
                            name: kcadmin
                            key: email
                restartPolicy: Never
            backoffLimit: 4

    - name: Delete the permanent admin user creation jobs
      kubernetes.core.k8s:
        state: absent
        api_version: batch/v1
        kind: Job
        name: kc-create-admin-user
        namespace: "{{ keycloak_namespace }}"

    - name: Delete the kcadmin secret
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Secret
        name: kcadmin
        namespace: "{{ keycloak_namespace }}"
