---
- delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: create the portal namespace
      kubernetes.core.k8s:
        name: "{{ portal_namespace }}"
        state: present
        kind: namespace
        api_version: v1

    - name: create the user-portal-config secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: secret
          type: generic
          metadata:
            name: "{{ portal_secret }}"
            namespace: "{{ portal_namespace }}"
          data:
            UI_BASE_URL: "{{ portal_ui_base_url }}"
            API_BASE_URL: "{{ portal_api_base_url }}"
            WS_BASE_URL: "{{ portal_ws_base_url }}"
            UID_NUMBER_OFFSET: "{{ portal_uid_number_offset }}"
            HMAC_KEY: "{{ portal_hmac_key }}"
            GOOGLE_ANALYTICS_ID: "{{ portal_google_analytics_id }}"
            SENTRY_DSN: "{{ portal_sentry_dsn }}"
            IRODS_HOST: "{{ irods_host }}"
            IRODS_ZONE_NAME: "{{ irods_zone }}"
            IRODS_PASSWORD: "{{ irods_password }}"
            IRODS_IPCSERVICES_ENABLED: "{{ irods_ipcservices_enabled }}"
            DB_HOST: "{{ portal_db_host }}"
            DB_PORT: "{{ portal_db_port }}"
            DB_USER: "{{ portal_db_user }}"
            DB_PASSWORD: "{{ portal_db_password }}"
            DB_NAME: "{{ portal_db_name }}"
            SESSION_SECRET: "{{ portal_session_secret }}"
            SESSION_SECURE_COOKIE: "{{ portal_session_secure_cookie }}"
            KEYCLOAK_REALM: "{{ portal_keycloak_realm }}"
            KEYCLOAK_AUTH_URL: "{{ portal_keycloak_auth_url }}"
            KEYCLOAK_CLIENT: "{{ portal_keycloak_client }}"
            KEYCLOAK_SECRET: "{{ portal_keycloak_keycloak_secret }}"
            LDAP_HOST: "{{ portal_ldap_host }}"
            LDAP_ADMIN: "{{ portal_ldap_admin }}"
            LDAP_PASSWORD: "{{ portal_ldap_password }}"
            LDAP_BASE_DN: "{{ portal_ldap_base_dn }}"
            LDAP_EVERYONE_GROUP: "{{ portal_ldap_everyone_group }}"
            BCC_NEW_ACCOUNT_CONFIRMATION: "{{ portal_bcc_new_account_confirmation }}"
            BCC_PASSWORD_CHANGE_REQUEST: "{{ portal_bcc_new_password_change_request }}"
            BCC_SERVICE_ACCESS_GRANTED: "{{ portal_bcc_service_access_granted }}"
            BCC_WORKSHOP_ENROLLMENT_REQUEST: "{{ portal_bcc_workshop_enrollment_request }}"
            INTERCOM_ENABLED: "{{ portal_intercom_enabled }}"
            INTERCOM_APP_ID: "{{ portal_intercom_app_id }}"
            INTERCOM_TOKEN: "{{ portal_intercom_token }}"
            INTERCOM_COMPANY_ID: "{{ portal_intercom_company_id }}"
            INTERCOM_ADMIN_USER_PORTAL_BOT_ID: "{{ portal_intercom_admin_user_portal_bot_id }}"
            INTERCOM_ADMIN_TIER1_ATMOSPHERE_ID: "{{ portal_intercom_admin_tier1_atmosphere_id }}"
            INTERCOM_ADMIN_TIER1_SCIENCE_TEAM_ID: "{{ portal_intercom_admin_tier1_science_team_id }}"
            INTERCOM_ADMIN_TIER1_DATA_WATCH_ID: "{{ portal_intercom_admin_tier1_data_watch_id }}"
            MAILMAN_ENABLED: "{{ portal_mailman_enabled }}"
            MAILMAN_URL: "{{ portal_mailman_url }}"
            MAILMAN_PASSWORD: "{{ portal_mailman_password }}"
            BISQUE_URL: "{{ portal_bisque_url }}"
            BISQUE_USER: "{{ portal_bisque_user }}"
            BISQUE_PASSWORD: "{{ portal_bisque_password }}"
            TERRAIN_URL: "{{ portal_terrain_url }}"
            TERRAIN_USER: "{{ portal_terrain_user }}"
            TERRAIN_PASSWORD: "{{ portal_terrain_password }}"
            PROFILE_UPDATE_PERIOD: "{{ portal_profile_update_period }}"
            PROFILE_WARNING_PERIOD: "{{ portal_profile_warning_period }}"
            PROFILE_UPDATE_TEXT: "{{ portal_profile_update_text }}"
            PROFILE_WARNING_TEXT: "{{ portal_profile_warning_text }}"
            SMTP_HOST: "{{ portal_smtp_host }}"
            SMTP_PORT: "{{ portal_smtp_port }}"
            SMTP_FROM: "{{ portal_smtp_from }}"
            SUPPORT_EMAIL: "{{ portal_support_email }}"

    - name: deploy the portal
