---
- name: Install and configure image cache
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Add the kube-fledged helm repo
      kubernetes.core.helm_repository:
        name: kubefledged-charts
        repo_url: https://senthilrch.github.io/kubefledged-charts/
        state: present

    - name: Install kube-fledged
      kubernetes.core.helm:
        name: image-cache
        chart_ref: kubefledged-charts/kube-fledged
        release_namespace: image-cache
        create_namespace: true
        state: present
        wait: true
        values:
          image:
            pullPolicy: IfNotPresent
          args:
            controllerImagePullDeadlineDuration: 30m
            controllerImageCacheRefreshFrequency: 1h

    - name: Create the harbor image pull secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ vice_image_pull_secret }}"
            namespace: image-cache
          type: kubernetes.io/dockerconfigjson
          data:
            ".dockerconfigjson": "{{ {'auths': {'harbor.cyverse.org': {'auth': (harbor_robot_name ~ ':' ~ harbor_robot_secret) | b64encode}}} | to_json | b64encode }}"

    - name: Add the actual image cache
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubefledged.io/v1alpha2
          kind: ImageCache
          metadata:
            name: vice-image-cache
            namespace: image-cache
            labels:
              app: kubefledged
              kubefledged: imagecache
          spec:
            imagePullSecrets:
              - name: vice-image-pull-secret
            cacheSpec:
              - images: "{{ vice_image_cache }}"
                nodeSelector:
                  analysis: "true"
