---
- name: Deploy service via skaffold
  tags:
    - deploy
  block:
    - name: Builds dir
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ build_json_dir }}"

    - name: Show the immediate parent's path
      debug:
        msg: "My parent is at {{ ansible_parent_role_paths[0] }}"

    - name: read the build JSON file
      delegate_to: localhost
      set_fact:
        build_json_path: "{{ build_json_dir + '/' + project_name + '.json'}}"
        build_json: "{{ lookup('file', build_json_dir +'/' + project_name + '.json') | from_json }}"

    - name: Image tag
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ build_json.builds[0].tag }}"

    - name: Run skaffold deploy
      delegate_to: localhost
      run_once: true
      ansible.builtin.command:
        chdir: "{{ skaffold_dir }}"
        cmd: >
          skaffold deploy
          --namespace "{{ deploy_ns | default(ns) }}"
          --build-artifacts "{{ build_json_path }}"
          --force
          --kubeconfig "{{ lookup('env', 'KUBECONFIG') }}"
          {% if deploy_profile is defined -%}
          --profile {{ deploy_profile }}
          {%- endif -%}
