---
- name: Check if haproxy is installed manually
  ansible.builtin.stat:
    path: /usr/local/sbin/haproxy
  register: h

- name: Debug | Haproxy_installed
  ansible.builtin.debug:
    var: h

- name: Install | Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present
  when: h.stat is not defined or not h.stat.exists

- name: Configure | Download dhparam
  ansible.builtin.get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/ssl/dhparam
    owner: root
    group: root
    mode: "0644"

- name: Configure | Template config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart haproxy
