---
- name: Create DE Kubernetes namespaces
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Create the namespaces for the DE and VICE
      kubernetes.core.k8s:
        api_version: v1
        state: present
        definition:
          kind: Namespace
          metadata:
            name: "{{ item }}"
            labels:
              has-vice-routes: "true"
      loop:
        - "{{ ns }}"
        - "{{ vice_ns }}"
