---
- name: Apply self-signed issuers
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Apply default-issuer
      kubernetes.core.k8s:
        state: present
        namespace: "{{ ns }}"
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: default-issuer
          spec:
            selfSigned: {}
