---
- name: Create the timezone configmap
  delegate_to: localhost
  run_once: true
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: timezone
        namespace: "{{ ns }}"
      data:
        timezone: "{{ timezone }}"
