apiVersion: skaffold/v3
kind: Config
metadata:
  name: terrain
build:
  artifacts:
    - image: harbor.cyverse.org/de/terrain
      custom:
        buildCommand: ./buildx-build.sh
        dependencies:
          paths: ["**"]
  tagPolicy:
    gitCommit: {}
  local: {}
  platforms:
    - "linux/amd64"
manifests:
  rawYaml:
    - k8s/terrain.yml
deploy:
  kubectl: {}
