---
- name: Install node feature discovery and nVidia device plugin
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Install the node-feature-discovery helm repo
      kubernetes.core.helm_repository:
        name: nfd
        repo_url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
        state: present

    - name: Install the nVidia helm repo
      kubernetes.core.helm_repository:
        name: nvdp
        repo_url: https://nvidia.github.io/k8s-device-plugin
        state: present

    - name: Install the node-feature-discovery chart
      kubernetes.core.helm:
        name: node-feature-discovery
        chart_ref: nfd/node-feature-discovery
        namespace: kube-system
        values:
          worker:
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
              - key: gpu
                operator: Equal
                value: "true"
                effect: NoSchedule
              - key: analysis
                operator: Equal
                value: only
                effect: NoSchedule
        wait: true

    - name: Install the nVidia device plugin chart
      kubernetes.core.helm:
        name: nvidia-device-plugin
        chart_ref: nvdp/nvidia-device-plugin
        chart_version: 0.17.1
        namespace: kube-system
        values:
          nfd:
            enabled: false
          gfd:
            enabled: true
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
            - key: gpu
              operator: Equal
              value: "true"
              effect: NoSchedule
            - key: analysis
              operator: Equal
              value: only
              effect: NoSchedule
        wait: true
