---
- name: Initialize portal database
  delegate_to: localhost
  block:
    - name: Create the portal db user
      community.postgresql.postgresql_user:
        login_host: "{{ groups['dbms'][0] }}"
        login_port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        login_db: "{{ pg_db }}"
        name: "{{ portal_db_user }}"
        password: "{{ portal_db_password }}"
      when: create_user is defined and create_user
      tags:
        - update-databases

    - name: Create the portal database
      community.postgresql.postgresql_db:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        name: "{{ portal_db_name }}"
        owner: "{{ portal_db_user }}"
        encoding: "{{ encoding }}"
        locale_provider: "icu"
        icu_locale: "{{ icu_locale }}"
        template: "{{ template }}"
      when: create_dbs is defined and create_dbs

    - name: Grant all privileges to the portal user
      community.postgresql.postgresql_privs:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        login_db: "{{ portal_db_name }}"
        grant_option: true
        privs: ALL
        type: schema
        objs: public
        role: "{{portal_db_user}}"
      tags:
        - update-databases

    - name: Grant the pg_read_server_files privilege to the portal user
      community.postgresql.postgresql_query:
        login_host: "{{groups['dbms'][0]}}"
        port: "{{pg_listen_port}}"
        login_user: "{{pg_login_user}}"
        login_password: "{{pg_login_password}}"
        login_db: "{{portal_db_name}}"
        query: "GRANT pg_read_server_files TO {{portal_db_user}}"
      tags:
        - update-databases

    - name: Install extensions for the portal database
      when: install_exts is defined and install_exts
      community.postgresql.postgresql_ext:
        login_host: "{{ groups['dbms'][0] }}"
        port: "{{ pg_listen_port }}"
        login_user: "{{ pg_login_user }}"
        login_password: "{{ pg_login_password }}"
        login_db: "{{ portal_db_name }}"
        name: "{{ item }}"
      loop:
        - moddatetime
        - btree_gist
        - insert_username
      tags:
        - update-databases

    - name: Checkout the portal repo for its migrations
      ansible.builtin.git:
        repo: "https://github.com/cyverse-de/portal2"
        dest: "{{ dbs_dir.path }}/portal2"
        clone: true
        update: true
        force: true
        version: "{{ portal_version }}"
      tags:
        - update-databases

    - name: Run portal repo migrations
      ansible.builtin.command: >
        {{ migrate_installed.stdout }}
        -database "postgresql://{{ portal_db_user }}:{{ portal_db_password }}@{{ groups['dbms'][0] }}:{{ pg_listen_port }}/{{ portal_db_name }}?sslmode=disable"
        -path "{{ dbs_dir.path }}/portal2/migrations"
        up
      when: migrate is defined and migrate
      tags:
        - update-databases

    - name: Check out the grid csv files
      ansible.builtin.git:
        repo: "{{grid_csv_repo}}"
        dest: "{{dbs_dir.path}}/grid_institutions"
        clone: yes
        update: yes
        force: yes
        version: "{{grid_csv_version}}"
      tags:
        - update-databases

    - name: Check for the 'Other' record in account_institution_grid
      community.postgresql.postgresql_query:
        login_host: "{{ groups['dbms'][0] }}"
        login_port: "{{ pg_listen_port }}"
        login_user: "{{ portal_db_user }}"
        login_password: "{{ portal_db_password }}"
        login_db: "{{ portal_db_name }}"
        query: SELECT grid_id FROM account_institution_grid WHERE name = 'Other'
      register: other_result
      tags:
        - update-databases

    - name: Show other_result debug output
      ansible.builtin.debug:
        msg: "{{ other_result }}"
      tags:
        - update-databases

    - name: Insert the Other field into the account_institution_grid table
      when: other_result.rowcount == 0
      community.postgresql.postgresql_query:
        login_host: "{{ groups['dbms'][0] }}"
        login_port: "{{ pg_listen_port }}"
        login_user: "{{ portal_db_user }}"
        login_password: "{{ portal_db_password }}"
        login_db: "{{ portal_db_name }}"
        query: INSERT INTO account_institution_grid (grid_id,name,city,state,country) VALUES ('', 'Other','','','') ON CONFLICT (grid_id) DO NOTHING
      tags:
        - update-databases

    - name: Check for records in account_institution_grid
      community.postgresql.postgresql_query:
        login_host: "{{ groups['dbms'][0] }}"
        login_port: "{{ pg_listen_port }}"
        login_user: "{{ portal_db_user }}"
        login_password: "{{ portal_db_password }}"
        login_db: "{{ portal_db_name }}"
        query: SELECT COUNT(*) AS record_count FROM account_institution_grid
      register: records_result
      tags:
        - update-databases

    - name: Show records_result debug output
    - debug:
        msg: "{{records_result}}"
      tags:
        - update-databases

    - name: Update pgpass so that we can use psql
      ansible.builtin.lineinfile:
        path: "{{ user_home }}/.pgpass"
        create: true
        insertafter: "EOF"
        mode: "0600"
        line: "{{ groups['dbms'][0] }}:*:*:{{ portal_db_user }}:{{ portal_db_password }}"
      vars:
        user_home: "{{ lookup('env', 'HOME') }}"
      tags:
        - update-databases

    - name: Copy grid.csv data into the account_institution_grid table
      when: records_result["query_result"][0]["record_count"] <= 1
      ansible.builtin.command:
        argv:
          - "psql"
          - "--host={{ groups['dbms'][0] }}"
          - "--port={{ pg_listen_port }}"
          - "--username={{ portal_db_user }}"
          - "--dbname={{ portal_db_name }}"
          - "--command={{ cmd }}"
      vars:
        column_list: "grid_id,name,city,state,country"
        grid_csv_path: "{{ dbs_dir.path }}/grid_institutions/grid.csv"
        table: "account_institution_grid"
        options: "DELIMITER ',', FORMAT 'csv', NULL 'null'"
        cmd: "\\copy {{table}} ({{column_list}}) from {{grid_csv_path}} WITH ({{options}})"
      tags:
        - update-databases
