---
- name: build the vice-operator image
  ansible.builtin.include_role:
    name: build-service
    tasks_from: main
  vars:
    project_name: vice-operator
    source_service: app-exposer
  tags:
    - build
