---
- name: Install the vice-operator
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Builds dir
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ build_json_dir }}"

    - name: Read the build JSON file
      delegate_to: localhost
      ansible.builtin.set_fact:
        build_json: "{{ lookup('file', build_json_dir + '/app-exposer.json') | from_json }}"

    - name: Image tag
      delegate_to: localhost
      ansible.builtin.debug:
        msg: "{{ build_json.builds[0].tag }}"

    - name: Render the template
      ansible.builtin.template:
        src: vice_operator.yml.j2
        dest: "/tmp/vice_operator_{{ vice_ns }}.yml"

    - name: set up the namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ vice_ns }}"

    - name: Set up the vice-operator service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: vice-operator
            namespace: "{{ vice_ns }}"

    - name: Set up vice-operator cluster role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: vice-operator
          rules:
            - apiGroups: [""]
              resources: ["persistentvolumes"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: [""]
              resources: ["nodes"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get"]

    - name: Set up the vice-operator role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: vice-operator
            namespace: "{{ vice_ns }}"
          rules:
            - apiGroups: [""]
              resources: ["pods", "pods/log", "services", "configmaps", "secrets", "persistentvolumeclaims"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["apps"]
              resources: ["deployments", "daemonsets"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["networking.k8s.io"]
              resources: ["networkpolicies"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["policy"]
              resources: ["poddisruptionbudgets"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["gateways", "httproutes"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["traefik.io"]
              resources: ["middlewares"]
              verbs: ["get", "list", "watch", "create", "update", "delete"]
            - apiGroups: ["coordination.k8s.io"]
              resources: ["leases"]
              verbs: ["get", "create", "update"]

    - name: Set up the cluster role binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: "vice-operator-{{ vice_ns }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: vice-operator
          subjects:
            - kind: ServiceAccount
              name: vice-operator
              namespace: "{{ vice_ns }}"

    - name: Set up the role binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: vice-operator
            namespace: "{{ vice_ns }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: vice-operator
          subjects:
            - kind: ServiceAccount
              name: vice-operator
              namespace: "{{ vice_ns }}"

    - name: Deploy the vice-operator
      kubernetes.core.k8s:
        state: present
        src: "/tmp/vice_operator_{{ vice_ns }}.yml"
      register: deployed

    - name: Remove rendered template
      ansible.builtin.file:
        path: "/tmp/vice_operator_{{ vice_ns }}.yml"
        state: absent
      when: deployed.changed
