---
- delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Create the vice-app-runner ServiceAccount
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: vice-app-runner
            namespace: "{{ vice_ns }}"
          automountServiceAccountToken: true

    - name: Create the configurator service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: configurator
            namespace: "{{ ns }}"
          automountServiceAccountToken: true

    - name: Create the app-exposer service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: app-exposer
            namespace: "{{ ns }}"
          automountServiceAccountToken: true

    - name: Create the vice-apps Role
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Role
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            namespace: "{{ vice_ns }}"
            name: vice-apps
          rules:
            - apiGroups: [""]
              resources: [""]
              verbs: [""]

    - name: Create the pod-reader role
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Role
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            namespace: "{{ ns }}"
            name: pod-reader
          rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "watch", "list"]

    - name: Create the configurator role RoleBinding
      kubernetes.core.k8s:
        state: present
        definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: read-pods
            namespace: "{{ ns }}"
          subjects:
            - kind: ServiceAccount
              name: configurator
              namespace: "{{ ns }}"
          roleRef:
            kind: Role
            name: pod-reader
            apiGroup: rbac.authorization.k8s.io

    - name: Create the app-exposer persistent volume provisioner cluster role binding
      kubernetes.core.k8s:
        state: present
        definition:
          kind: ClusterRoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: app-exposer-persistent-volume-provisioner
          subjects:
            - kind: ServiceAccount
              namespace: "{{ ns }}"
              name: app-exposer
          roleRef:
            kind: ClusterRole
            name: system:persistent-volume-provisioner
            apiGroup: rbac.authorization.k8s.io

    - name: Create the app-exposer cluster role binding
      kubernetes.core.k8s:
        state: present
        definition:
          kind: ClusterRoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: app-exposer
          subjects:
            - kind: ServiceAccount
              namespace: "{{ ns }}"
              name: app-exposer
          roleRef:
            kind: ClusterRole
            name: admin
            apiGroup: rbac.authorization.k8s.io

    - name: Create the httproute-admin cluster role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: httproute-admin
          rules:
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete

    - name: Create the app-exposer httproute admin cluster role binding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: app-exposer-httproute-admin
          subjects:
            - kind: ServiceAccount
              namespace: "{{ ns }}"
              name: app-exposer
          roleRef:
            kind: ClusterRole
            name: httproute-admin
            apiGroup: rbac.authorization.k8s.io

    - ansible.builtin.include_role:
        name: deploy-service
        tasks_from: main
      vars:
        project_name: app-exposer
