---
- name: Configure maintenance-page
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  block:
    - name: Create the maintenance-page service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: maintenance-page
            namespace: "{{ ns }}"

    - name: Create the maintenance page cluster role
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: maintenance-page
          rules:
            - apiGroups: [""]
              resources: ["services"]
              verbs: ["get", "create"]
            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["httproutes"]
              verbs: ["get", "update"]

    - name: Create the ClusterRoleBinding for the maintenance-page
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: maintenance-page
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: maintenance-page
          subjects:
            - kind: ServiceAccount
              name: maintenance-page
              namespace: "{{ ns }}"

    - name: Deploy maintenance-page service
      ansible.builtin.include_role:
        name: deploy-service
        tasks_from: main
      vars:
        project_name: maintenance-page
