apiVersion: skaffold/v3
kind: Config
metadata:
  name: de-mailer
build:
  artifacts:
    - image: harbor.cyverse.org/de/de-mailer
      custom:
        buildCommand: ./buildx-build.sh
        dependencies:
          paths: ["**"]
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/de-mailer.yml
deploy:
  kubectl: {}
