---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Set firewall fact
  ansible.builtin.set_fact:
    active_firewall: >-
      {% if ansible_facts.services['firewalld.service'] is defined
          and ansible_facts.services['firewalld.service'].state == 'running' %}firewalld
      {%- elif ansible_facts.services['ufw.service'] is defined
            and ansible_facts.services['ufw.service'].state == 'running' %}ufw
      {%- else %}none{% endif %}

- name: Open the API Port
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ k8s_api_port }}" # k0s api
    - "9443" # join api
    - "8132" # konnectivity
  when: active_firewall == "ufw"

- name: Open the API port
  become: true
  ansible.posix.firewalld:
    permanent: true
    immediate: true
    zone: public
    state: enabled
    port: "{{ item }}"
  notify: Reload firewalld
  with_items:
    - "{{ k8s_api_port }}/tcp" # k0s api port
    - "9443/tcp" # join api port
    - "8132/tcp" # konnectivity server
  when: active_firewall == "firewalld"

- name: Configure k8s haproxy settings
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    append_newline: true
    prepend_newline: true
    marker: "# {mark} K8S HAProxy Settings"
    block: "{{ lookup('template', '00_k8s.cfg.j2') }}"
  notify: Restart haproxy
