---
- hosts: dbms
  become: false
  connection: local
  roles:
    - role: db_staging
      tasks_from: prepare.yml

    - role: postgresql_init
      tasks_from: portal.yml

    - role: db_staging
      tasks_from: cleanup.yml
