---
- hosts: dbms
  become: false
  connection: local
  tasks:
    - ansible.builtin.import_role:
        name: db_staging
        tasks_from: prepare.yml

    - ansible.builtin.import_role:
        name: postgresql_init
        tasks_from: portal.yml

    - ansible.builtin.import_role:
        name: db_staging
        tasks_from: cleanup.yml
