---
- name: system updates
  hosts: k8s_workers
  become: true
  serial: 5
  tasks:
    - name: print host
      become: false
      debug:
        var: inventory_hostname

    - name: update packages
      ansible.builtin.shell: yum update -y --disablerepo=kubernetes
      when: ansible_os_family == "RedHat"

    - name: update debian/ubuntu packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        state: latest
        name: "*"
      when: ansible_os_family == "Debian"


- name: system updates
  hosts: k8s_controllers
  become: true
  serial: 1
  tasks:
    - name: print host
      become: false
      debug:
        var: inventory_hostname

    - name: update packages
      ansible.builtin.shell: yum update -y --disablerepo=kubernetes
      when: ansible_os_family == "RedHat"

    - name: update debian/ubuntu packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        state: latest
        name: "*"
      when: ansible_os_family == "Debian"