---
- name: bootstrap EKS cluster and supporting services
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - role: vice-operator-eks
  tags:
    - vice-operator-eks

- name: install the iRODS CSI driver
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - role: kubernetes_irods_csi_driver
  tags:
    - irods-csi-driver

- name: deploy vice-operator
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - role: vice-operator
  tags:
    - vice-operator
