---
- name: Load secrets into Kubernetes
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  block:
    - name: Set repo_dir fact
      ansible.builtin.set_fact:
        repo_dir: "{{ inventory_dir | dirname }}"
    - name: Set secrets_dir fact
      ansible.builtin.set_fact:
        secrets_dir: "{{ [repo_dir, secrets_loader_base_dir] | path_join }}/"
    - name: Debug repo and secrets directories
      ansible.builtin.debug:
        msg: "repo dir: '{{ repo_dir }}', secrets_dir: '{{ secrets_dir }}'"
    - name: Generate gpg data
      ansible.builtin.set_fact:
        gpg_data: "{{ gpg_data | default({}) | combine({item | basename: lookup('file', secrets_dir + item) | b64encode}) }}"
      with_items: "{{ secrets_loader_gpg_filepaths }}"
      when: secrets_loader_load_gpg_secret

    - name: Load gpg secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secrets_loader_gpg_secret }}"
            namespace: "{{ ns }}"
          data: "{{ gpg_data }}"
      when: secrets_loader_load_gpg_secret

    - name: Generate signing keys data
      ansible.builtin.set_fact:
        signing_keys_data: "{{ signing_keys_data | default({}) | combine({item | basename: lookup('file', secrets_dir + item) | b64encode}) }}"
      with_items: "{{ secrets_loader_signing_keys_filepaths }}"
      when: secrets_loader_load_signing_keys_secret

    - name: Load signing keys secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secrets_loader_signing_keys_secret }}"
            namespace: "{{ ns }}"
          data: "{{ signing_keys_data }}"
      when: secrets_loader_load_signing_keys_secret

    - name: Generate accepted keys data
      ansible.builtin.set_fact:
        accepted_keys_data: "{{ accepted_keys_data | default({}) | combine({item | basename: lookup('file', secrets_dir + item, rtrim=false) | b64encode}) }}"
      with_items: "{{ secrets_loader_accepted_keys_filepaths }}"
      when: secrets_loader_load_accepted_keys_secret

    - name: Load accepted keys secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secrets_loader_accepted_keys_secret }}"
            namespace: "{{ ns }}"
          data: "{{ accepted_keys_data }}"
      when: secrets_loader_load_accepted_keys_secret

    - name: Generate ssl data
      ansible.builtin.set_fact:
        ssl_data: "{{ ssl_data | default({}) | combine({item | basename: lookup('file', secrets_dir + item) | b64encode}) }}"
      with_items: "{{ secrets_loader_ssl_filepaths }}"
      when: secrets_loader_load_ssl_secret

    - name: Load ssl secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secrets_loader_ssl_secret }}"
            namespace: "{{ ns }}"
          data: "{{ ssl_data }}"
      when: secrets_loader_load_ssl_secret
