---
- name: remove the discoenv ingress
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "discoenv"
        namespace: "{{ ns }}"

- name: remove the portal ingress
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: portal-ingress
        namespace: "{{ ns }}"
