---
- name: Remove the discoenv ingress
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "discoenv"
        namespace: "{{ ns }}"

- name: Remove the portal ingress
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: portal-ingress
        namespace: "{{ ns }}"
