---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Set firewall fact
  ansible.builtin.set_fact:
    active_firewall: >-
      {% if ansible_facts.services['firewalld.service'] is defined
          and ansible_facts.services['firewalld.service'].state == 'running' %}firewalld
      {%- elif ansible_facts.services['ufw.service'] is defined
            and ansible_facts.services['ufw.service'].state == 'running' %}ufw
      {%- else %}none{% endif %}

- name: Open postgresql port using ufw
  community.general.ufw:
    rule: allow
    port: 5432
    proto: tcp
  when: active_firewall == "ufw"

- name: Open postgresql port using firewalld
  ansible.posix.firewalld:
    permanent: true
    zone: public
    state: enabled
    port: "5432/tcp"
  when: active_firewall == "firewalld"
  notify: reload firewalld

- name: Install on Debian family systems
  block:
    - apt:
        update_cache: true
        pkg:
          - "postgresql-{{dbms_postgresql_version}}"
          - "postgresql-client-{{dbms_postgresql_version}}"
          - "python3-psycopg2"
        state: present

    - name: configure | ensure postgres user owns home dir
      file:
        path: /var/lib/postgresql
        state: directory
        owner: postgres
        group: postgres
        recurse: true
  when: ansible_os_family == "Debian"

- name: install postgresql and postgresql-server
  block:
    - ansible.builtin.package:
        state: present
        name: "{{ item }}"
      with_items:
        - "postgresql-server-{{dbms_postgresql_version}}"
        - "postgresql-{{dbms_postgresql_version}}"
        - "postgresql-contrib"
        - "python-psycopg2"

    - name: red hat | run initdb
      ansible.builtin.command:
        cmd: /usr/bin/postgresql-setup --initdb
        creates: "/var/lib/pgsql/data"
      notify:
        - restart postgres
  when: ansible_os_family == "RedHat"
